name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust:
    name: Build and distribute Charon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: AeneasVerif/charon

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Build
        run: make build-charon-rust

      - name: Compute tag name
        id: tag_name
        run: echo "TAG_NAME=$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT" >> $GITHUB_OUTPUT

      - name: Create tag
        if: github.ref == 'refs/heads/master'
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
          tag: master-${{ steps.tag_name.outputs.TAG_NAME }}

      - name: Debug
        run: |
          echo "1: $HOME"
          ls /home/runner
          echo "2"
          ls /home/runner/charon
          echo "3"
          ls /home/runner/charon/bin

      - name: Release charon
        if: github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/charon/bin/charon
          asset_name: charon
          tag: master-${{ steps.tag_name.outputs.TAG_NAME }}

      - name: Release charon-driver
        if: github.ref == 'refs/heads/master'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/charon/bin/charon-driver
          asset_name: charon-driver
          tag: master-${{ steps.tag_name.outputs.TAG_NAME }}
